server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

  spring:
    profiles:
      active: native
    data:
      mongodb:
        uri: mongodb://localhost:27017/microservicesEBAC
        database: produto
        auto-index-creation: true